export const ITEM_HOME_REQUEST = "ITEM_HOME_REQUEST";
export const ITEM_HOME_SUCCESS = "ITEM_HOME_SUCCESS";
export const ITEM_HOME_FAIL = "ITEM_HOME_FAIL";

export const ITEM_COMMENT_FETCH_FAIL = "ITEM_COMMENT_FETCH_FAIL";
export const ITEM_COMMENT_FETCH_SUCCESS = "ITEM_COMMENT_FETCH_SUCCESS";
export const ITEM_COMMENT_FETCH_REQUEST = "ITEM_COMMENT_FETCH_REQUEST";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";

export const ITEM_CREATE_REQUEST = "ITEM_CREATE_REQUEST";
export const ITEM_CREATE_SUCCESS = "ITEM_CREATE_SUCCESS";
export const ITEM_CREATE_FAIL = "ITEM_CREATE_FAIL";

export const ITEM_FETCH_REQUEST = "ITEM_FETCH_REQUEST";
export const ITEM_FETCH_SUCCESS = "ITEM_FETCH_SUCCESS";
export const ITEM_FETCH_FAIL = "ITEM_FETCH_FAIL";
export const ITEM_FETCH_RESET = "ITEM_FETCH_RESET";
